# -*- coding: utf-8 -*-
"""assignment a0.1_danial022.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPkOw5jPocrMyfm_XdYqOFVNN3Rq5u9i

# 1.variable types
## Task1
"""

# convert celsius to farenheit

c = float(27.54)
f = c * 9/5 + 32
print(f"{c}C = {f:.4f}F")

"""## Task2"""

# Tiny Calculator: operations on int & float
x = 14
y = 4.5

print(f"Sum: {x + y}")
print(f"Difference: {x - y}")
print(f"Product: {x * y}")
print(f"True Division: {x / y:.2f}")
print(f"Floor Division: {x // y}")

"""# 2.containers
##Task1
"""

# crocery  basket
shoping_list = []

item = input("Enter 4 grocery item(separate each with a comma: )").split(",")
shoping_list = item

immutable_basket = tuple(shoping_list)


print(f"your immutable basket: {immutable_basket}")
print(f"third item: {immutable_basket[2]}")

"""## Task2"""

# word state

sample = "to be you me to be to"
word = sample.split()

unique_word  = set(word)

word_count = {}
for w in word:
  if w in word_count:
    word_count[w] += 1
  else:
    word_count[w] = 1

print(f"unique word: {unique_word}")
print(f"word count: {word_count}")

"""# 3.Functions

##Task1
"""

def is_prime(n: int):
  if n < 2:
    return False
  for i in range(2, n):
    if n % i == 0:
      return False
  return True

num = int(input("Enter a Number: "))
if is_prime(num):
  print(f"{num} is a prime number")
else:
  print(f"{num} it is not prime number")

"""##Task2"""

def greet(name: str, time: int = 1) -> None:
    word = name.capitalize()
    print(' '.join([word] * time))

name_input = input("whats your name: ")
time_input = int(input("how many time do you want to greet: "))

greet(name_input, time_input)

"""# 4.classes

## Task1
"""

class counter:
  def __init__(self):
    self.count = 0

  def increment(self, step = 1):
    self.count += step

  def value(self):
    return self.count

c = counter()
for _ in range(5):
    c.increment()
print(c.value())

"""##Task2"""

import math

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def distance_to(self, other):
        dx = self.x - other.x
        dy = self.y - other.y
        return math.sqrt(dx**2 + dy**2)

p = Point(6, 10)
q = Point(0, 0)
assert round(p.distance_to(q), 1)
print(round(p.distance_to(q), 1))