# -*- coding: utf-8 -*-
"""Assignment 01_farshidshariatnezhad/.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CKjN5Nny_N4XSf9SBL3Szw4Vg3l8gBm
"""

# دریافت دمای سلسیوس به صورت متن
celsius_temp = input("Enter temperature in Celsius: ")

# تبدیل دما به float
celsius_temp = float(celsius_temp)

# محاسبه دما به فارنهایت
fahrenheit_temp = (celsius_temp * 9/5) + 32

# چاپ نتیجه به صورت فرمت‌شده
print(f"The temperature is {celsius_temp}°C, which is {fahrenheit_temp:.2f}°F.")

# ذخیره دو عدد از انواع مختلف
num_int = 5         # عدد صحیح
num_float = 3.2     # عدد اعشاری

# محاسبه و چاپ عملیات‌ها
sum_result = num_int + num_float
difference_result = num_int - num_float
product_result = num_int * num_float
true_division_result = num_int / num_float
floor_division_result = num_int // num_float

# چاپ نتایج
print(f"Sum: {sum_result}")
print(f"Difference: {difference_result}")
print(f"Product: {product_result}")
print(f"True Division: {true_division_result}")
print(f"Floor Division: {floor_division_result}")

# 1. شروع با یک لیست خالی
shopping_list = []

# 2. اضافه کردن حداقل 4 آیتم به لیست از ورودی کاربر
shopping_list_input = input("Enter at least 4 items (comma-separated): ")
shopping_list = shopping_list_input.split(',')  # تبدیل ورودی به لیست

# 3. تبدیل لیست به تاپل به نام immutable_basket
immutable_basket = tuple(shopping_list)

# 4. چاپ سومین آیتم از تاپل
print(f"The third item in the basket is: {immutable_basket[2]}")

sample = "to be or not to be that is the question"

# 1. ساخت یک set برای کلمات منحصر به فرد
unique_words = set(sample.split())

# 2. ساخت یک دیکشنری برای شمارش تعداد تکرار هر کلمه
word_counts = {}
for word in sample.split():
    word_counts[word] = word_counts.get(word, 0) + 1

# 3. چاپ هر دو ساختار داده
print("Unique Words (set):", unique_words)
print("Word Counts (dict):", word_counts)

# توضیح تفاوت اصلی:
# - Set تنها کلمات منحصر به فرد را نگه می‌دارد و ترتیب کلمات مهم نیست.
# - Dictionary هر کلمه را به تعداد تکرار آن مرتبط می‌کند و ترتیب در آن حفظ می‌شود.

import math

def is_prime(n: int) -> bool:
    """
    Return True if n is a prime number, else False.
    0 and 1 are *not* prime.
    """
    # 0 و 1 اعداد اول نیستند
    if n <= 1:
        return False

    # چک کردن تقسیم‌پذیری از 2 تا √n
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False  # اگر به عددی غیر از 1 و خود n تقسیم شد، عدد اول نیست

    return True  # اگر هیچ تقسیم‌پذیری پیدا نشد، عدد اول است

# Quick self-check
print([x for x in range(10) if is_prime(x)])   # Expected: [2, 3, 5, 7]

def greet(name: str, times: int = 1) -> None:
    """Print `name`, capitalised, exactly `times` times on one line."""
    # تبدیل نام به حرف بزرگ و چاپ آن times بار
    print(" ".join([name.capitalize()] * times))

# تست کد:
greet("alice")          # Alice
greet("bob", times=3)   # Bob Bob Bob

class Counter:
    """Counts how many times `increment` is called."""

    def __init__(self):
        # 1. شمارنده داخلی را با مقدار 0 مقداردهی اولیه می‌کنیم
        self.count = 0

    def increment(self, step: int = 1):
        # 2. به شمارنده مقدار step را اضافه می‌کنیم
        self.count += step

    def value(self):
        # 3. مقدار فعلی شمارنده را برمی‌گردانیم
        return self.count

# تست کد:
c = Counter()
for _ in range(5):
    c.increment()
print(c.value())   # Expected: 5

import math

class Point:
    """
    A 2-D point supporting distance calculation.
    Usage:
        p = Point(3, 4)
        q = Point(0, 0)
        print(p.distance_to(q))  # 5.0
    """

    def __init__(self, x: float, y: float):
        # 1. ذخیره مختصات x و y به عنوان ویژگی‌ها
        self.x = x
        self.y = y

    def distance_to(self, other: 'Point') -> float:
        # 2. محاسبه فاصله با استفاده از فرمول اقلیدسی
        return math.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)

# Smoke test
p, q = Point(3, 4), Point(0, 0)
assert round(p.distance_to(q), 1) == 5.0