# -*- coding: utf-8 -*-
"""Copy of Assignment 01. Python | Nexus | RezaShokrzad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkMJLhjA6cqvmZv5bAwCpr92ALLC6ACY

# 📚 Assignment 1 — Python Fundamentals

<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------
Welcome to your first hands-on practice! This set of four mini-projects walks you through the basics every Python (and ML) developer leans on daily:

1. Variable types

2. Core containers

3. Functions

4. Classes

Each part begins with quick pointers, then gives you two bite-sized tasks to code. Replace every # TODO with working Python and run your script or notebook to check the result. Happy hacking! 😊

## 1. Variable Types 🧮
**Quick-start notes**

* Primitive types: `int`, `float`, `str`, `bool`

* Use `type(obj)` to inspect an object’s type.

* Casting ↔ converting: `int("3")`, `str(3.14)`, `bool(0)`, etc.

### Task 1 — Celsius → Fahrenheit
"""

# 👉 a Celsius temperature (as text), convert it to float,
#    compute Fahrenheit (°F = °C * 9/5 + 32) and print a nicely formatted line.
# TODO:

celsius_text = "26.0"
celsius_float = float(celsius_text)
fahrenheit = celsius_float * 9/5 + 32
print(f"The tempreture is {celsius_float}°C, which is {fahrenheit}°F.")

"""### Task 2 — Tiny Calculator

"""

# 👉 Store two numbers of **different types** (one int, one float),
#    then print their sum, difference, product, true division, and floor division.
# TODO:
int_num = 10
float_num = 3.5
print(f"sum {int_num + float_num}")
print(f"difference {int_num - float_num}")
print(f"product {int_num * float_num}")
print(f"true division {int_num / float_num}")
print(f"floor division {int_num // float_num}")

"""## 2. Containers 📦 (list, tuple, set, dict)
**Quick-start notes**

| Container | Mutable? | Ordered?                      | Typical use                       |
| --------- | -------- | ----------------------------- | --------------------------------- |
| `list`    | ✔        | ✔                             | Growth, indexing, slicing         |
| `tuple`   | ✖        | ✔                             | Fixed-size records, hashable keys |
| `set`     | ✔        | ✖                             | Deduplication, membership tests   |
| `dict`    | ✔        | ✖ (3.7 + preserves insertion) | Key → value look-ups              |

### Task 1 — Grocery Basket
"""

# Start with an empty shopping list (list).
# 1. Append at least 4 items supplied in one line of user input (comma-separated).
# 2. Convert the list to a *tuple* called immutable_basket.
# 3. Print the third item using tuple indexing.
# TODO:
shopping_list = []
user_input = input("Enter at least 4 items, separated by commas: ")
items = [item.strip() for item in user_input.split(',')]
shopping_list.extend(items)
print(f"Your shopping list: {shopping_list}")
immutable_basket = tuple(shopping_list)
print(f"The immutable tuple: {immutable_basket}")
if len(immutable_basket) >= 3:
    print(f"The third item is: {immutable_basket[2]}")
else:
    print("Not enough items in the basket to get the third item.")

"""### Task 2 — Word Stats"""

sample = "to be or not to be that is the question"

# 1. Build a set `unique_words` containing every distinct word.
# 2. Build a dict `word_counts` mapping each word to the number of times it appears.
#    (Hint: .split() + a simple loop)
# 3. Print the two structures and explain (in a comment) their main difference.
# TODO:
unique_words = "to be or not to be that is the question."

word_counts = text.lower().replace('.', '').split()

unique_words = set(words)

word_counts = {}

for word in words:
    word_counts[word] = word_counts.get(word, 0) + 1

print("Unique words (set):")
print(unique_words)
print("\nWord counts (dictionary):")
print(word_counts)

# A set stores only unique, unordered elements and is highly optimized for checking if
# an item is present. A dictionary stores key-value pairs, which is perfect for
# mapping each unique word to its corresponding count.

"""## 3. Functions 🔧
**Quick-start notes**

* Define with `def`, return with `return`.

* Parameters can have default values.

* Docstrings (`''' … '''`) document behaviour.

### Task 1 — Prime Tester
"""

def is_prime(n: int) -> bool:
    """
    Return True if n is a prime number, else False.
    0 and 1 are *not* prime.
    """
    # TODO: replace pass with your implementation
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True


# Quick self-check
print([x for x in range(10) if is_prime(x)])   # Expected: [2, 3, 5, 7]

"""### Task 2 — Repeater Greeter"""

def greet(name: str, times: int = 1) -> None:
    """Print `name`, capitalised, exactly `times` times on one line."""
    # TODO:
    capitalized_name = name.capitalize()
    print(' '.join([capitalized_name] * times))

greet("alice")          # Alice
greet("bob", times=3)   # Bob Bob Bob

"""## 4. Classes 🏗️
**Quick-start notes**

* Create with class Name:

* Special method __init__ runs on construction.

* self refers to the instance; attributes live on self.

### Task 1 — Simple Counter
"""

class Counter:
    """Counts how many times `increment` is called."""
    # TODO:
    # 1. In __init__, store an internal count variable starting at 0.
    # 2. Method increment(step: int = 1) adds `step` to the count.
    # 3. Method value() returns the current count.

    def __init__(self):
        self.count = 0

    def increment(self, step: int = 1) -> None:
        self.count += step

    def value(self) -> int:
        return self.count


c = Counter()
for _ in range(5):
    c.increment()
print(c.value())   # Expected: 5

"""### Task 2 — 2-D Point with Distance"""

import math

class Point:
    """
    A 2-D point supporting distance calculation.
    Usage:
        p = Point(3, 4)
        q = Point(0, 0)
        print(p.distance_to(q))  # 5.0
    """
    # TODO:
    # 1. Store x and y as attributes.
    # 2. Implement distance_to(other) using the Euclidean formula.

    def __init__(self, x: float, y: float) -> None:
        self.x = x
        self.y = y

    def distance_to(self, other: 'Point') -> float:
        """Calculates the Euclidean distance to another Point."""
        dx = self.x - other.x
        dy = self.y - other.y
        return math.sqrt(dx**2 + dy**2)


# Smoke test
p, q = Point(3, 4), Point(0, 0)
assert round(p.distance_to(q), 1) == 5.0
print(p.distance_to(q))