import pandas as pd
df = pd.read_csv('E:/Nexus/Nexus_Assignments/Exercises/access.csv')
print(df.head(4))
print(df.tail(2))
print(df.shape)
print(df.columns)
print(df.columns.tolist())
print(df.dtypes)
print(df.info())
df.to_feather('access.feather')
df2 = pd.read_feather('access.feather')
print(df2.head())
df3 = pd.read_parquet('titanic.parquet')
print(df3.head())
df4 = pd.read_json('fruits.json')
print(df4.head())
df4.to_excel('fruits.xlsx')
df5 = pd.read_excel('fruits.xlsx')
print(df5.head())
# import nltk
# nltk.download('punkt')
# nltk.download('punkt_tab')